name: Generate Snake Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"

  # Allows manual trigger from Actions tab
  workflow_dispatch:

  # Run on every push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jayeshmepani
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit and push the generated files to main branch
      - name: Commit and push snake files
        run: |
          cp dist/*.svg .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-contribution-grid-snake*.svg
          git diff --staged --quiet || git commit -m "Update snake animation"
          git push
